-- MySQL Script generated by MySQL Workbench
-- Thu Mar 14 11:29:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(100) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `email_token` VARCHAR(255) NULL DEFAULT NULL,
  `password` CHAR(255) NOT NULL,
  `register_at` DATETIME NULL,
  `connexion_at` DATETIME NULL DEFAULT NULL,
  `rank` TINYINT(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_email` (`email`),
  UNIQUE INDEX `unique_pseudo` (`pseudo`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

--
-- Déchargement des données de la table `user`
--

INSERT INTO `user` (`id`, `pseudo`, `email`, `email_token`, `password`, `register_at`, `connexion_at`, `rank`) VALUES
(4, 'admin', 'admin@yostmail.com', NULL, '$2y$12$255mUws1dmzCIGPat1a2TuxPZqk6KZXSnIWscV2mzZfbqQ58dciB.', '2019-01-18 21:10:00', NULL, 2),
(13, 'test4', 'test4@yopmail.com', NULL, '$2y$12$JLK/.vZ8bFDxlVzsB6qTneIMNZ3ZoAOX4aW84GUIANSveZ3tlNftW', '2019-02-21 16:25:44', NULL, 2);


-- -----------------------------------------------------
-- Table `blog`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`article` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `chapo` TEXT NOT NULL,
  `content` TEXT NOT NULL,
  `publication_date` DATETIME NOT NULL,
  `update_date` DATETIME NULL DEFAULT NULL,
  `author_id` INT(10) UNSIGNED NULL,
  `update_by` INT(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_article` (`author_id`),
  INDEX `index_date_article` USING BTREE (`publication_date`),
  CONSTRAINT `fk_user_article`
    FOREIGN KEY (`author_id`)
    REFERENCES `blog`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

--
-- Déchargement des données de la table `article`
--

INSERT INTO `article` (`id`, `title`, `chapo`, `content`, `publication_date`, `update_date`, `author_id`, `update_by`) VALUES
(1, 'L;homme doit explorer, et c&#39;est l&#39;exploration à son meilleur', 'Les problèmes semblent puissants à partir de 150 miles', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In laoreet sit amet ligula in mattis. Aenean imperdiet vehicula massa, at viverra ex molestie sit amet. Morbi tortor ipsum, efficitur quis tempor eget, tincidunt ac ligula. Suspendisse potenti. Nullam augue diam, convallis in sem quis, pharetra finibus leo. Aliquam erat volutpat. Cras nec felis id odio interdum pretium hendrerit eget elit. In suscipit lobortis lacus sit amet posuere. Ut laoreet maximus lorem, eget suscipit lectus eleifend in. Donec ac lorem diam. Vivamus varius finibus congue. Sed vitae finibus urna, et congue nisi.&nbsp;', '2019-03-13 13:24:12', NULL, 13, 13),
(2, 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel tellus et quam eleifend aliquet at a leo. Praesent feugiat fringilla risus, non gravida quam bibendum ut.', 'Vivamus non scelerisque sem. Ut aliquam sem sapien, et egestas nulla vestibulum vel. Nunc maximus imperdiet posuere. Donec consectetur risus et mattis vehicula. Maecenas efficitur enim placerat, feugiat metus sit amet, consequat nulla. Phasellus tristique sapien eu congue placerat. Duis consectetur semper ligula mollis pretium. Sed at ex nunc. Integer eu nunc quis arcu rhoncus feugiat quis quis augue. Ut suscipit metus ut velit rhoncus, eu rutrum elit varius. Ut vestibulum dui id ante convallis, interdum blandit diam ullamcorper.&nbsp;', '2019-03-13 13:29:50', NULL, 13, NULL);

-- --------------------------------------------------------

-- -----------------------------------------------------
-- Table `blog`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`comment` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `comments` TEXT NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `comment_date` DATETIME NOT NULL,
  `validated` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `article_id` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_article_id_idx` (`article_id`),
  CONSTRAINT `fk_article_id`
    FOREIGN KEY (`article_id`)
    REFERENCES `blog`.`article` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
